{include resources/header.md}
{set-property title "Trivial HTTP User's Guide"}
{set-property docs-package trivial-http}

# Trivial-HTTP User's Guide

# Table of Contents 

{table-of-contents :start 2 :depth 3}

## Introduction

If your HTTP needs are simple (trivial, even), then you've
come to the right place. If, on some other hand, you're
looking for a full featured HTTP Client with all the bell's
and whistles, then you should seek out [Drakma][].

<div class='reference'>
    
## Reference

### HTTP Basics

{docs http-get}
{docs http-download}
{docs http-resolve}
{docs http-post}
{docs http-head}

### Utilities

{docs header-value}
{docs header-pair}
{docs escape-url-query}

</div>

## Indices

{docs-index :all}

<hr>

{include resources/footer.md}
