{set-property html yes}
{set-property author "Gary Warren King"}
{set-property style-sheet user-guide}
{set-property title "Trivial HTTP User's Guide"}
{set-property docs-package trivial-http}

<div id="header">
{include navigation.md}
</div>

{include shared.md}

# Trivial-HTTP User's Guide

# Table of Contents 

{table-of-contents :start 2 :depth 3}

## Introduction

If your HTTP needs are simple (trivial, even), then you've
come to the right place. If, on some other hand, you're
looking for a full featured HTTP Client with all the bell's
and whistles, then you should seek out [Drakma][].

<div class='reference'>
    
## Reference

### HTTP Basics

{docs http-get}
{docs http-download}
{docs http-resolve}
{docs http-post}
{docs http-head}

### Utilities

{docs header-value}
{docs header-pair}
{docs escape-url-query}

</div>

## Indices

{docs-index :all}

<hr>

<div id="footer">
<span id="copyright"> Copyright (c) 2005 - 2011 Gary Warren King (gwking@metabang.com)</span> 
<span id="license-note">metabang-bind has an MIT style license</span>
<span id="timestamp">Last updated {today} at {now}</span>
</div>

